# Generated by Django 4.0.5 on 2022-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='download_authorization',
            field=models.CharField(default='0CSBwiduTNfyVMQm6mEYlEbmysOau6e', max_length=300),
            preserve_default=False,
        ),
    ]
