# Generated by Django 4.0.5 on 2022-06-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_download_authorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='download_authorization',
        ),
    ]
